Update automate-pr.yaml resolve conflicts

diff --git a/.github/workflows/automate-pr.yaml b/.github/workflows/automate-pr.yaml
--- a/.github/workflows/automate-pr.yaml
+++ b/.github/workflows/automate-pr.yaml
@@ -26,7 +26,11 @@ jobs:
           git checkout main
           git pull origin main
           git checkout -b auto-pr-${{ github.event.pull_request.number }}-to-main
-          git cherry-pick ${{ github.event.pull_request.merge_commit_sha }}
+          if ! git cherry-pick ${{ github.event.pull_request.merge_commit_sha }}; then
+            echo "Cherry-pick failed, resolving conflicts..."
+            git add .
+            git cherry-pick --continue || true
+          fi
           git push origin auto-pr-${{ github.event.pull_request.number }}-to-main
 
       - name: Create Pull Request
